stages:
  - common

common:
  stage: common
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker build -t registry.gitlab.com/ruzanowski/ubiquitous/common ./src/BuildingBlocks/U.Common
    - docker push registry.gitlab.com/ruzanowski/ubiquitous/common