image: mcr.microsoft.com/dotnet/core/sdk:2.2.301

stages:
  - deploy_common

common:
  stage: deploy_common
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  before_script:
    - chmod -R a+x ./src/BuildingBlocks/Common/scripts
  script:
    - ./src/BuildingBlocks/Common/scripts/dotnet-nuget-push.sh
    - ./src/BuildingBlocks/Common/scripts/dotnet-publish.sh
