image: mcr.microsoft.com/dotnet/core/sdk:2.2.301

stages:
  - build
  - test
  - performance
  - deploy

# takes upwards of 10 minutes, make manual
code_quality:
  stage: test
  when: manual
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker pull codeclimate/codeclimate
    - docker run
      --env CODECLIMATE_DEBUG=1
      --env CODECLIMATE_CODE="$PWD"
      --volume "$PWD":/code
      --volume /var/run/docker.sock:/var/run/docker.sock
      --volume /tmp/cc:/tmp/cc
      codeclimate/codeclimate analyze -f html > report.html
    #- cat report.html
  artifacts:
    paths: [report.html]
  dependencies: []
  except:
    variables:
      - $CODE_QUALITY_DISABLED

build:
  stage: build
  before_script:
    - 'dotnet restore'
  #  - 'npm install'
  script:
    - 'dotnet build'
  #    - 'chmod -R +x ./scripts'
  #    - 'scripts/run-tests.bat'

release:
  stage: deploy
  artifacts:
    paths:
      - publish/
  script:
    - 'chmod -R +x .'
    # The output path is relative to the position of the csproj-file
    - ./publish-all.sh

include:
    - local: src/BuildingBlocks/Common/.gitlab-ci.yml
    - local: src/BuildingBlocks/U.EventBus/.gitlab-ci.yml
    - local: src/BuildingBlocks/U.EventBus.RabbitMQ/.gitlab-ci.yml
    - local: src/BuildingBlocks/U.IntegrationEventLog/.gitlab-ci.yml
    - local: src/Services/Fetch/U.FetchService/.gitlab-ci.yml
    - local: src/Services/Generator/U.GeneratorService/.gitlab-ci.yml
    - local: src/Services/Identity/U.IdentityService/.gitlab-ci.yml
    - local: src/Services/Notification/U.NotificationService/.gitlab-ci.yml
    - local: src/Services/Product/U.ProductService/.gitlab-ci.yml
    - local: src/Services/Subscription/U.SubscriptionService/.gitlab-ci.yml
    - local: src/Services/ApiGateway/U.ApiGateway/.gitlab-ci.yml
    - local: src/Adapters/SmartStore/U.SmartStoreAdapter/.gitlab-ci.yml
#    - local: ci/Browser-Performance.gitlab-ci.yml
#    - local: ci/Container-Scanning.gitlab-ci.yml
#    - local: ci/Dependency-Scanning.gitlab-ci.yml
#    - local: ci/License-Management.gitlab-ci.yml
#    - local: ci/SAST.gitlab-ci.yml