image: mcr.microsoft.com/dotnet/core/sdk:2.2.301

stages:
  - build
  - test
  - performance
  - myget_common
  - myget_eventbus
  - myget_eventbus_rabbitmq
  - myget_integrationeventlog
  - deploy
  - docker_deploy

build:
  stage: build
  before_script:
    - 'dotnet restore'
  #  - 'npm install' todo
  script:
    - 'dotnet build'
#    - 'chmod -R +x ./scripts'
#    - 'scripts/run-tests.bat' todo

code_quality:
  stage: test
  when: manual
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker pull codeclimate/codeclimate
    - docker run
      --env CODECLIMATE_DEBUG=1
      --env CODECLIMATE_CODE="$PWD"
      --volume "$PWD":/code
      --volume /var/run/docker.sock:/var/run/docker.sock
      --volume /tmp/cc:/tmp/cc
      codeclimate/codeclimate analyze -f html > report.html
  artifacts:
    paths: [report.html]
  dependencies: []
  except:
    variables:
      - $CODE_QUALITY_DISABLED

MyGet_Common:
  stage: myget_common
  before_script:
    - 'cd src/BuildingBlocks/Common'
    - chmod -R a+x ./scripts
  script:
    - ./scripts/dotnet-restore.sh
    - ./scripts/dotnet-build.sh
    - ./scripts/dotnet-publish.sh
    - ./scripts/dotnet-nuget-push.sh

MyGet_EventBus:
  stage: myget_eventbus
  before_script:
    - 'cd src/BuildingBlocks/U.EventBus'
    - chmod -R a+x ./scripts
  script:
    - ./scripts/dotnet-restore.sh
    - ./scripts/dotnet-build.sh
    - ./scripts/dotnet-publish.sh
    - ./scripts/dotnet-nuget-push.sh

MyGet_EventBus_RabbitMQ:
  stage: myget_eventbus_rabbitmq
  before_script:
    - 'cd src/BuildingBlocks/U.EventBus.RabbitMQ'
    - chmod -R a+x ./scripts
  script:
    - ./scripts/dotnet-restore.sh
    - ./scripts/dotnet-build.sh
    - ./scripts/dotnet-publish.sh
    - ./scripts/dotnet-nuget-push.sh

MyGet_IntegrationEventLog:
  stage: myget_integrationeventlog
  before_script:
    - 'cd src/BuildingBlocks/U.IntegrationEventLog'
    - chmod -R a+x ./scripts
  script:
    - ./scripts/dotnet-restore.sh
    - ./scripts/dotnet-build.sh
    - ./scripts/dotnet-publish.sh
    - ./scripts/dotnet-nuget-push.sh


fetchservice:
  stage: deploy
  before_script:
    - 'cd src/Services/Fetch/U.FetchService'
    - chmod -R a+x ./scripts
  script:
    - ./scripts/dotnet-restore.sh
    - ./scripts/dotnet-publish.sh

deploy_fetchservice:
  stage: docker_deploy
  image: docker:17.06.0-ce
  services:
    - docker:17.06.0-ce-dind
  before_script:
    - 'cd src/Services/Fetch/U.FetchService'
    - docker info
    - apk update
    - apk upgrade
    - apk add python python-dev py-pip build-base
    - pip install docker-compose
    - docker login -u $CI_REGISTRY_USER -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - docker build -t registry.gitlab.com/ruzanowski/ubiquitous/fetchservice:${DOCKER_TAG} ./src/Services/Fetch/U.FetchService
    - docker push registry.gitlab.com/ruzanowski/ubiquitous/fetchservice:${DOCKER_TAG}

include:
#    - local: src/Services/Generator/U.GeneratorService/.gitlab-ci.yml
#    - local: src/Services/Identity/U.IdentityService/.gitlab-ci.yml
#    - local: src/Services/Notification/U.NotificationService/.gitlab-ci.yml
#    - local: src/Services/Product/U.ProductService/.gitlab-ci.yml
#    - local: src/Services/Subscription/U.SubscriptionService/.gitlab-ci.yml
#    - local: src/ApiGateway/.gitlab-ci.yml
#    - local: src/Adapters/SmartStore/U.SmartStoreAdapter/.gitlab-ci.yml
#    - local: ci/Browser-Performance.gitlab-ci.yml
#    - local: ci/Container-Scanning.gitlab-ci.yml
#    - local: ci/Dependency-Scanning.gitlab-ci.yml
#    - local: ci/License-Management.gitlab-ci.yml
#    - local: ci/SAST.gitlab-ci.yml