version: "3.5"

services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: elk/elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - 'discovery.type=single-node'
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    restart: unless-stopped
    volumes:
      - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch:/usr/share/elasticsearch/data
      - elasticsearchlogs:/usr/share/elasticsearch/logs
    networks:
      - ubiquitous

  logstash:
    container_name: logstash
    build:
      context: elk/logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./elk/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "9450:9450"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    restart: unless-stopped
    networks:
      - ubiquitous
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  kibana:
    container_name: kibana
    build:
      context: elk/kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - ubiquitous
    restart: unless-stopped
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  jaeger-collector:
    container_name: jaeger-collector
    image: jaegertracing/jaeger-collector
    ports:
      - "14269:14269"
      - "14268:14268"
      - "14267:14267"
      - "9411:9411"
    networks:
      - ubiquitous
    restart: unless-stopped
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    command: ["--span-storage.type=elasticsearch", "--es.server-urls=http://elasticsearch:9200", "--es.tags-as-fields.all=true", "--es.num-shards=1",  "--log-level=error" ]
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  jaeger-agent:
    container_name: jaeger-agent
    hostname: jaeger-agent
    image: jaegertracing/jaeger-agent
    command: ["--collector.host-port=jaeger-collector:14267" ]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    networks:
      - ubiquitous
    restart: unless-stopped
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    depends_on:
      - jaeger-collector
      - elasticsearch
    links:
      - jaeger-collector
      - elasticsearch

  jaeger-query:
    container_name: jaeger-query
    hostname: jaeger-query
    image: jaegertracing/jaeger-query
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    ports:
      - "16686:16686"
      - "16687:16687"
    networks:
      - ubiquitous
    restart: unless-stopped
    command: ["--span-storage.type=elasticsearch", "--es.server-urls=http://elasticsearch:9200", "--es.sniffer=false", "--log-level=debug"]
    depends_on:
      - jaeger-agent
    links:
      - jaeger-agent

volumes:
  elasticsearch:
    driver: local
  elasticsearchlogs:
    driver: local
  logstash:
    driver: local
  kibana:
    driver: local
  jaeger-query:
    driver: local
  jaeger-agent:
    driver: local
  jaeger-collector:
    driver: local

networks:
  ubiquitous:
    name: ubiquitous
    external: true