version: "3.5"

services:
  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    build:
      context: elk/elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    restart: unless-stopped
    volumes:
      - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch:/usr/share/elasticsearch/data
      - elasticsearchlogs:/usr/share/elasticsearch/logs
    networks:
      - ubiquitous

  logstash:
    container_name: logstash
    hostname: logstash
    build:
      context: elk/logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./elk/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "9450:9450"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    restart: unless-stopped
    networks:
      - ubiquitous
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    hostname: kibana
    build:
      context: elk/kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - ubiquitous
    restart: unless-stopped
    depends_on:
      - elasticsearch

volumes:
  elasticsearch:
    driver: local
  elasticsearchlogs:
    driver: local
  logstash:
    driver: local
  kibana:
    driver: local

networks:
  ubiquitous:
    name: ubiquitous
    external: true