version: "3.5"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    ports:
      - 9000:9000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - ubiquitous
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ubiquitous.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
    - postgres
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - 5450:80
    networks:
      - ubiquitous
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - ubiquitous

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    command:
    [
        "redis-server",
        "--bind",
        "redis",
        "--port",
        "6379"
    ]
    volumes:
      - redis:/data
    restart: unless-stopped
    networks:
      - ubiquitous

  consul:
    image: consul
    container_name: consul
    ports:
      - 8500:8500
    restart: unless-stopped
    volumes:
      - consul:/consul/data
    networks:
      - ubiquitous

  fabio:
    image: fabiolb/fabio
    container_name: fabio
    environment:
    - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
    ports:
    - 9998:9998
    - 9999:9999
    restart: unless-stopped
    networks:
      - ubiquitous

  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - '8086:8086'
    volumes:
      - influxdb:/var/lib/influxdb
    networks:
      - ubiquitous

volumes:
  portainer:
    driver: local
  rabbitmq:
    driver: local
  redis:
    driver: local
  postgres:
    driver: local
  pgadmin:
    driver: local
  consul:
    driver: local
  fabio:
    driver: local
  influxdb:
    driver: local

networks:
  ubiquitous:
    name: ubiquitous
    external: true