version: "3.5"

services:
  u.smartstore-adapter:
    image: u.smartstore_adapter:latest
    container_name: u.smartstore-adapter
    build:
      context: .
      dockerfile: src/Adapters/SmartStore/U.SmartStoreAdapter/Dockerfile
    ports:
      - 5100:5100
    environment:
      DbOptions__Connection: Server=postgres;Port=5432;Database=smartstore-adapter;User Id=postgres;Password=postgres;Integrated Security=true;Pooling=true;
      DbOptions__Type: Npgsql
      ASPNETCORE_URLS: http://+:5100
      ASPNETCORE_ENVIRONMENT: docker
    networks:
      - ubiquitous

  u.fetch-service:
    image: u.fetch-service:latest
    container_name: u.fetch-service
    build:
      context: .
      dockerfile: src/Services/Fetch/U.FetchService/Dockerfile
    ports:
      - 5200:5200
    environment:
      DbOptions__Connection: Server=postgres;Port=5432;Database=fetch-service;User Id=postgres;Password=postgres;Integrated Security=true;Pooling=true;
      DbOptions__Type: Npgsql
      IntegrationEventLogConnection: Server=postgres;Port=5432;Database=IntegrationEventLog;User Id=postgres;\nPassword=postgres;Integrated Security=true;Pooling=true;
      ASPNETCORE_URLS: http://+:5200
      ASPNETCORE_ENVIRONMENT: docker
    depends_on:
      - u.smartstore-adapter
    networks:
      - ubiquitous

  u.product-service:
    image: u.product-service:latest
    container_name: u.product-service
    build:
      context: .
      dockerfile: src/Services/Product/U.ProductService/Dockerfile
    ports:
      - 5000:5000
    environment:
      DbOptions__Connection: Server=postgres;Port=5432;Database=product-service;User Id=postgres;Password=postgres;Integrated Security=true;Pooling=true;
      DbOptions__Type: Npgsql
      IntegrationEventLogConnection: Server=postgres;Port=5432;Database=IntegrationEventLog;User Id=postgres;\nPassword=postgres;Integrated Security=true;Pooling=true;
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: docker
    networks:
      - ubiquitous

  u.report-service:
    image: u.report-service:latest
    container_name: u.report-service
    build:
      context: .
      dockerfile: src/Services/Report/U.ReportService/Dockerfile
    ports:
      - 5300:5300
    environment:
      ASPNETCORE_URLS: http://+:5300
      ASPNETCORE_ENVIRONMENT: docker
    networks:
      - ubiquitous

networks:
  ubiquitous:
    name: ubiquitous
    external: true