version: "3.5"

services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - ubiquitous
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ubiquitous.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
    - postgres
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - 5450:80
    networks:
      - ubiquitous
    restart: unless-stopped

  mongo:
    container_name: mongo
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - ubiquitous

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes: 
      - rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes: 
      - redis:/data
    networks:
      - ubiquitous

  u.smartstore-adapter:
    image: u.smartstore_adapter:latest
    container_name: u.smartstore-adapter
    build:
      context: .
      dockerfile: Adapters/SmartStore/U.SmartStoreAdapter/Dockerfile
    ports:
      - 5100:5100
    environment:
      DbOptions__Connection: Server=postgres;Port=5432;Database=smartstore-adapter;User Id=postgres;Password=postgres;Integrated Security=true;Pooling=true;
      DbOptions__Type: Npgsql
      ASPNETCORE_URLS: http://+:5100
      ASPNETCORE_ENVIRONMENT: docker
    networks:
      - ubiquitous

  u.fetch-service:
    image: u.fetch-service:latest
    container_name: u.fetch-service
    build:
      context: .
      dockerfile: Services/Fetch/U.FetchService/Dockerfile
    ports:
      - 5200:5200
    environment:
      DbOptions__Connection: Server=postgres;Port=5432;Database=fetch-service;User Id=postgres;Password=postgres;Integrated Security=true;Pooling=true;
      DbOptions__Type: Npgsql
      IntegrationEventLogConnection: Server=postgres;Port=5432;Database=IntegrationEventLog;User Id=postgres;\nPassword=postgres;Integrated Security=true;Pooling=true;
      ASPNETCORE_URLS: http://+:5200
      ASPNETCORE_ENVIRONMENT: docker
    depends_on:
      - u.smartstore-adapter
    networks:
      - ubiquitous

  u.product-service:
    image: u.product-service:latest
    container_name: u.product-service
    build:
      context: .
      dockerfile: Services/Product/U.ProductService/Dockerfile
    ports:
      - 5000:5000
    environment:
      DbOptions__Connection: Server=postgres;Port=5432;Database=product-service;User Id=postgres;Password=postgres;Integrated Security=true;Pooling=true;
      DbOptions__Type: Npgsql
      IntegrationEventLogConnection: Server=postgres;Port=5432;Database=IntegrationEventLog;User Id=postgres;\nPassword=postgres;Integrated Security=true;Pooling=true;
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: docker
    networks:
      - ubiquitous

volumes:
  mongo:
    driver: local
  rabbitmq:
    driver: local
  redis:
    driver: local
  postgres:
    driver: local
  pgadmin:
    driver: local

networks:
  ubiquitous:
    name: ubiquitous
    external: true