stages:
  - build

subscriptionservice:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  stage: build
  script:
    - docker build -t registry.gitlab.com/ruzanowski/ubiquitous/subscriptionservice ./src/Services/Subscription/U.SubscriptionService
    - docker push registry.gitlab.com/ruzanowski/ubiquitous/subscriptionservice