stages:
  - deploy

subscriptionservice:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  stage: deploy
  before_script:
    - chmod -R a+x scripts
  script:
    - ./scripts/dotnet-publish.sh
    - ./scripts/docker-publish.sh
