image: gitlab/dind
stages:
  - build

subscription_service_registry_deploy:
  stage: build
  script:
    - 'docker build -t registry.gitlab.com/ruzanowski/ubiquitous/subscriptionservice .'
    - 'docker push registry.gitlab.com/ruzanowski/ubiquitous/subscriptionservice'