stages:
  - integrationeventlog

integrationeventlog:
  stage: integrationeventlog
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  script:
    - docker build -t registry.gitlab.com/ruzanowski/ubiquitous/integrationeventlog ./src/BuildingBlocks/U.IntegrationEventLog
    - docker push registry.gitlab.com/ruzanowski/ubiquitous/integrationeventlog