stages:
  - build

apigateway:
  stage: build
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker build -t registry.gitlab.com/ruzanowski/ubiquitous/apigateway ./src/ApiGateway
    - docker push registry.gitlab.com/ruzanowski/ubiquitous/apigateway