stages:
  - build

identityservice:
  stage: build
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker build -t registry.gitlab.com/ruzanowski/ubiquitous/identityservice ./src/Services/Identity/U.IdentityService
    - docker push registry.gitlab.com/ruzanowski/ubiquitous/identityservice