stages:
  - build

notificationservice:
  stage: build
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  script:
    - docker build -t registry.gitlab.com/ruzanowski/ubiquitous/notificationservice ./src/Services/Notification/U.NotificationService
    - docker push registry.gitlab.com/ruzanowski/ubiquitous/notificationservice