stages:
  - build

productservice:
  stage: build
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - 'docker build -t registry.gitlab.com/ruzanowski/ubiquitous/productservice .'
    - 'docker push registry.gitlab.com/ruzanowski/ubiquitous/productservice'