image: docker:19.03.1
stages:
  - build

eventbus.rabbitmq:
  stage: build
  services:
    - docker:19.03.1-dind
  script:
    - 'docker build -t registry.gitlab.com/ruzanowski/ubiquitous/eventbus.rabbitmq .'
    - 'docker push registry.gitlab.com/ruzanowski/ubiquitous/eventbus.rabbimq'