stages:
  - build

generatorservice:
  stage: build
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker build -t registry.gitlab.com/ruzanowski/ubiquitous/generatorservice ./src/Services/Generator/U.GeneratorService
    - docker push registry.gitlab.com/ruzanowski/ubiquitous/generatorservice