stages:
  - deploy_eventbus

eventbus:
  stage: deploy_eventbus
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  before_script:
    - chmod -R a+x scripts
  script:
    - ./scripts/dotnet-pack.sh
    - ./scripts/dotnet-nuget-push.sh