stages:
  - build

smartstoreadapter:
  stage: build
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker build -t registry.gitlab.com/ruzanowski/ubiquitous/smartstoreadapter ./src/Adapters/SmartStore/U.SmartStoreAdapter
    - docker push registry.gitlab.com/ruzanowski/ubiquitous/smartstoreadapter